// Post-build script: copies the Cloudflare Worker entry + its assets to dist/client/
// so Cloudflare Pages picks up _worker.js and all its dependencies resolve correctly.
import { copyFileSync, existsSync, mkdirSync, readdirSync, rmSync, statSync } from "fs";
import { join } from "path";

function copyDir(src, dest) {
  if (!existsSync(src)) return;
  mkdirSync(dest, { recursive: true });
  for (const entry of readdirSync(src)) {
    const srcPath = join(src, entry);
    const destPath = join(dest, entry);
    if (statSync(srcPath).isDirectory()) {
      copyDir(srcPath, destPath);
    } else {
      copyFileSync(srcPath, destPath);
    }
  }
}

// 1. Auto-detect the worker entry point (server.js or index.js)
const candidates = ["dist/server/server.js", "dist/server/index.js"];
const src = candidates.find(existsSync);

if (!src) {
  console.error(`ERROR: No worker entry found. Tried: ${candidates.join(", ")}`);
  process.exit(1);
}

const dest = "dist/client/_worker.js";
copyFileSync(src, dest);
console.log(`✅ Copied ${src} → ${dest}`);

// 2. Merge server assets INTO dist/client/assets/
copyDir("dist/server/assets", "dist/client/assets");
console.log("✅ Merged dist/server/assets → dist/client/assets");

// 3. CRITICAL: Delete dist/client/wrangler.json so Cloudflare Pages deploy
//    phase does NOT redirect away from wrangler.toml to this auto-generated file.
const badWrangler = "dist/client/wrangler.json";
if (existsSync(badWrangler)) {
  rmSync(badWrangler);
  console.log(`🗑️  Deleted ${badWrangler} (prevents deploy redirect)`);
}

// 4. CRITICAL: Delete entire .wrangler/ directory generated by @cloudflare/vite-plugin
//    This prevents deploy phase from redirecting to dist/client/wrangler.json
const deployDir = ".wrangler";
if (existsSync(deployDir)) {
  rmSync(deployDir, { recursive: true, force: true });
  console.log("🗑️  Deleted .wrangler/ (forces deploy to use wrangler.toml)");
}

