/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRepliesRouteImport } from './routes/_authenticated/replies'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated/jobs'
import { Route as AuthenticatedCallsRouteImport } from './routes/_authenticated/calls'
import { Route as AuthenticatedBridgeRouteImport } from './routes/_authenticated/bridge'
import { Route as AuthenticatedAgentRouteImport } from './routes/_authenticated/agent'
import { Route as ApiPublicShopifyWebhookRouteImport } from './routes/api/public/shopify-webhook'
import { Route as ApiPublicCallWebhookRouteImport } from './routes/api/public/call-webhook'
import { Route as AuthenticatedOrdersIdRouteImport } from './routes/_authenticated/orders.$id'
import { Route as ApiPublicBridgeResultRouteImport } from './routes/api/public/bridge.result'
import { Route as ApiPublicBridgePollRouteImport } from './routes/api/public/bridge.poll'
import { Route as ApiPublicBridgeIncomingRouteImport } from './routes/api/public/bridge.incoming'
import { Route as ApiPublicBridgeHeartbeatRouteImport } from './routes/api/public/bridge.heartbeat'
import { Route as ApiPublicAgentRunRouteImport } from './routes/api/public/agent.run'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRepliesRoute = AuthenticatedRepliesRouteImport.update({
  id: '/replies',
  path: '/replies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCallsRoute = AuthenticatedCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBridgeRoute = AuthenticatedBridgeRouteImport.update({
  id: '/bridge',
  path: '/bridge',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgentRoute = AuthenticatedAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicShopifyWebhookRoute = ApiPublicShopifyWebhookRouteImport.update({
  id: '/api/public/shopify-webhook',
  path: '/api/public/shopify-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCallWebhookRoute = ApiPublicCallWebhookRouteImport.update({
  id: '/api/public/call-webhook',
  path: '/api/public/call-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrdersIdRoute = AuthenticatedOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedOrdersRoute,
} as any)
const ApiPublicBridgeResultRoute = ApiPublicBridgeResultRouteImport.update({
  id: '/api/public/bridge/result',
  path: '/api/public/bridge/result',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgePollRoute = ApiPublicBridgePollRouteImport.update({
  id: '/api/public/bridge/poll',
  path: '/api/public/bridge/poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgeIncomingRoute = ApiPublicBridgeIncomingRouteImport.update({
  id: '/api/public/bridge/incoming',
  path: '/api/public/bridge/incoming',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgeHeartbeatRoute =
  ApiPublicBridgeHeartbeatRouteImport.update({
    id: '/api/public/bridge/heartbeat',
    path: '/api/public/bridge/heartbeat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAgentRunRoute = ApiPublicAgentRunRouteImport.update({
  id: '/api/public/agent/run',
  path: '/api/public/agent/run',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/agent': typeof AuthenticatedAgentRoute
  '/bridge': typeof AuthenticatedBridgeRoute
  '/calls': typeof AuthenticatedCallsRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/replies': typeof AuthenticatedRepliesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/api/public/call-webhook': typeof ApiPublicCallWebhookRoute
  '/api/public/shopify-webhook': typeof ApiPublicShopifyWebhookRoute
  '/api/public/agent/run': typeof ApiPublicAgentRunRoute
  '/api/public/bridge/heartbeat': typeof ApiPublicBridgeHeartbeatRoute
  '/api/public/bridge/incoming': typeof ApiPublicBridgeIncomingRoute
  '/api/public/bridge/poll': typeof ApiPublicBridgePollRoute
  '/api/public/bridge/result': typeof ApiPublicBridgeResultRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/agent': typeof AuthenticatedAgentRoute
  '/bridge': typeof AuthenticatedBridgeRoute
  '/calls': typeof AuthenticatedCallsRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/replies': typeof AuthenticatedRepliesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/': typeof AuthenticatedIndexRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/api/public/call-webhook': typeof ApiPublicCallWebhookRoute
  '/api/public/shopify-webhook': typeof ApiPublicShopifyWebhookRoute
  '/api/public/agent/run': typeof ApiPublicAgentRunRoute
  '/api/public/bridge/heartbeat': typeof ApiPublicBridgeHeartbeatRoute
  '/api/public/bridge/incoming': typeof ApiPublicBridgeIncomingRoute
  '/api/public/bridge/poll': typeof ApiPublicBridgePollRoute
  '/api/public/bridge/result': typeof ApiPublicBridgeResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/agent': typeof AuthenticatedAgentRoute
  '/_authenticated/bridge': typeof AuthenticatedBridgeRoute
  '/_authenticated/calls': typeof AuthenticatedCallsRoute
  '/_authenticated/jobs': typeof AuthenticatedJobsRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRouteWithChildren
  '/_authenticated/replies': typeof AuthenticatedRepliesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/api/public/call-webhook': typeof ApiPublicCallWebhookRoute
  '/api/public/shopify-webhook': typeof ApiPublicShopifyWebhookRoute
  '/api/public/agent/run': typeof ApiPublicAgentRunRoute
  '/api/public/bridge/heartbeat': typeof ApiPublicBridgeHeartbeatRoute
  '/api/public/bridge/incoming': typeof ApiPublicBridgeIncomingRoute
  '/api/public/bridge/poll': typeof ApiPublicBridgePollRoute
  '/api/public/bridge/result': typeof ApiPublicBridgeResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/agent'
    | '/bridge'
    | '/calls'
    | '/jobs'
    | '/orders'
    | '/replies'
    | '/settings'
    | '/templates'
    | '/orders/$id'
    | '/api/public/call-webhook'
    | '/api/public/shopify-webhook'
    | '/api/public/agent/run'
    | '/api/public/bridge/heartbeat'
    | '/api/public/bridge/incoming'
    | '/api/public/bridge/poll'
    | '/api/public/bridge/result'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/agent'
    | '/bridge'
    | '/calls'
    | '/jobs'
    | '/orders'
    | '/replies'
    | '/settings'
    | '/templates'
    | '/'
    | '/orders/$id'
    | '/api/public/call-webhook'
    | '/api/public/shopify-webhook'
    | '/api/public/agent/run'
    | '/api/public/bridge/heartbeat'
    | '/api/public/bridge/incoming'
    | '/api/public/bridge/poll'
    | '/api/public/bridge/result'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/agent'
    | '/_authenticated/bridge'
    | '/_authenticated/calls'
    | '/_authenticated/jobs'
    | '/_authenticated/orders'
    | '/_authenticated/replies'
    | '/_authenticated/settings'
    | '/_authenticated/templates'
    | '/_authenticated/'
    | '/_authenticated/orders/$id'
    | '/api/public/call-webhook'
    | '/api/public/shopify-webhook'
    | '/api/public/agent/run'
    | '/api/public/bridge/heartbeat'
    | '/api/public/bridge/incoming'
    | '/api/public/bridge/poll'
    | '/api/public/bridge/result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicCallWebhookRoute: typeof ApiPublicCallWebhookRoute
  ApiPublicShopifyWebhookRoute: typeof ApiPublicShopifyWebhookRoute
  ApiPublicAgentRunRoute: typeof ApiPublicAgentRunRoute
  ApiPublicBridgeHeartbeatRoute: typeof ApiPublicBridgeHeartbeatRoute
  ApiPublicBridgeIncomingRoute: typeof ApiPublicBridgeIncomingRoute
  ApiPublicBridgePollRoute: typeof ApiPublicBridgePollRoute
  ApiPublicBridgeResultRoute: typeof ApiPublicBridgeResultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/replies': {
      id: '/_authenticated/replies'
      path: '/replies'
      fullPath: '/replies'
      preLoaderRoute: typeof AuthenticatedRepliesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calls': {
      id: '/_authenticated/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof AuthenticatedCallsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bridge': {
      id: '/_authenticated/bridge'
      path: '/bridge'
      fullPath: '/bridge'
      preLoaderRoute: typeof AuthenticatedBridgeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agent': {
      id: '/_authenticated/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AuthenticatedAgentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/shopify-webhook': {
      id: '/api/public/shopify-webhook'
      path: '/api/public/shopify-webhook'
      fullPath: '/api/public/shopify-webhook'
      preLoaderRoute: typeof ApiPublicShopifyWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/call-webhook': {
      id: '/api/public/call-webhook'
      path: '/api/public/call-webhook'
      fullPath: '/api/public/call-webhook'
      preLoaderRoute: typeof ApiPublicCallWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/orders/$id': {
      id: '/_authenticated/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AuthenticatedOrdersIdRouteImport
      parentRoute: typeof AuthenticatedOrdersRoute
    }
    '/api/public/bridge/result': {
      id: '/api/public/bridge/result'
      path: '/api/public/bridge/result'
      fullPath: '/api/public/bridge/result'
      preLoaderRoute: typeof ApiPublicBridgeResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/poll': {
      id: '/api/public/bridge/poll'
      path: '/api/public/bridge/poll'
      fullPath: '/api/public/bridge/poll'
      preLoaderRoute: typeof ApiPublicBridgePollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/incoming': {
      id: '/api/public/bridge/incoming'
      path: '/api/public/bridge/incoming'
      fullPath: '/api/public/bridge/incoming'
      preLoaderRoute: typeof ApiPublicBridgeIncomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/heartbeat': {
      id: '/api/public/bridge/heartbeat'
      path: '/api/public/bridge/heartbeat'
      fullPath: '/api/public/bridge/heartbeat'
      preLoaderRoute: typeof ApiPublicBridgeHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/run': {
      id: '/api/public/agent/run'
      path: '/api/public/agent/run'
      fullPath: '/api/public/agent/run'
      preLoaderRoute: typeof ApiPublicAgentRunRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedOrdersRouteChildren {
  AuthenticatedOrdersIdRoute: typeof AuthenticatedOrdersIdRoute
}

const AuthenticatedOrdersRouteChildren: AuthenticatedOrdersRouteChildren = {
  AuthenticatedOrdersIdRoute: AuthenticatedOrdersIdRoute,
}

const AuthenticatedOrdersRouteWithChildren =
  AuthenticatedOrdersRoute._addFileChildren(AuthenticatedOrdersRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAgentRoute: typeof AuthenticatedAgentRoute
  AuthenticatedBridgeRoute: typeof AuthenticatedBridgeRoute
  AuthenticatedCallsRoute: typeof AuthenticatedCallsRoute
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRouteWithChildren
  AuthenticatedRepliesRoute: typeof AuthenticatedRepliesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgentRoute: AuthenticatedAgentRoute,
  AuthenticatedBridgeRoute: AuthenticatedBridgeRoute,
  AuthenticatedCallsRoute: AuthenticatedCallsRoute,
  AuthenticatedJobsRoute: AuthenticatedJobsRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRouteWithChildren,
  AuthenticatedRepliesRoute: AuthenticatedRepliesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicCallWebhookRoute: ApiPublicCallWebhookRoute,
  ApiPublicShopifyWebhookRoute: ApiPublicShopifyWebhookRoute,
  ApiPublicAgentRunRoute: ApiPublicAgentRunRoute,
  ApiPublicBridgeHeartbeatRoute: ApiPublicBridgeHeartbeatRoute,
  ApiPublicBridgeIncomingRoute: ApiPublicBridgeIncomingRoute,
  ApiPublicBridgePollRoute: ApiPublicBridgePollRoute,
  ApiPublicBridgeResultRoute: ApiPublicBridgeResultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
